### ISSUE TITLE
Icons can't be resolved when reusing components

### ISSUE THREAD

**Issue by archived-m** [WelcometoMyGarden/components#2]
https://github.com/WelcometoMyGarden/components/blob/6be6ae72eae3ca3eb3ddb80d852db4b9b75d3281/src/components/Input.svelte#L19

@auloin any quick thoughts on why this import would be failing when trying to import this component?

`Failed to resolve import "../images/icons" from "node_modules/<path>"`

**Comment by auloin** [comment]
I'm guessing that's because `src/images` is not published. It should be fixed if you add the path to the `files` field in `package.json`. I should have done it, sorry.

**Comment by MichielLeyman** [comment]
Thanks for the quick response, fixed in https://github.com/WelcometoMyGarden/components/commit/f78523bbd9df7841a3c664960b75f54f56582400
